export const categoriesInPortuguese: Record<string, string> = {
  Religion: "Religião",
  Inspirational: "Inspirador",
  "Family & Relationships": "Família e Relacionamentos",
  "Love & Romance": "Amor e Romance",
  Psychological: "Psicologia",
  Women: "Mulheres",
  "Literary Collections": "Coleções Literárias",
  Letters: "Cartas",
  "Social Science": "Ciências Sociais",
  "Feminism & Feminist Theory": "Feminismo e Teoria Feminista",
  "Women's Studies": "Estudos de Gênero Feminino",
  "Biography & Autobiography": "Biografia e Autobiografia",
  "Cultural, Ethnic & Regional": "Cultura, Etnia e Região",
  "African American & Black": "Afro-americano e Negro",
  "Political Science / General": "Ciência Política",
  "Romantic Comedy": "Comédia Romântica",
  Philosophy: "Filosofia",
  Spirituality: "Espiritualidade",
  Essays: "Ensaios",
  "Life Sciences": "Ciências Biológicas",
  Biology: "Biologia",
  Classics: "Clássicos",
  Astronomy: "Astronomia",
  Fantasy: "Fantasia",
  "Dark Fantasy": "Fantasia Sombria",
  "Literary Figures": "Figuras Literárias",
  Fiction: "Ficção",
  Nonfiction: "Não Ficção",
  Science: "Ciência",
  "Health & Fitness": "Saúde e Bem-estar",
  "Self-Help": "Autoajuda",
  Computers: "Computação",
  Technology: "Tecnologia",
  Education: "Educação",
  History: "História",
  Art: "Arte",
  Photography: "Fotografia",
  Travel: "Viagem",
  Cooking: "Culinária",
  Humor: "Humor",
  Drama: "Drama",
  Horror: "Terror",
  Poetry: "Poesia",
  "Business & Economics": "Negócios e Economia",
  Law: "Direito",
  Music: "Música",
  "Sports & Recreation": "Esportes e Lazer",
  "Comics & Graphic Novels": "Quadrinhos e Novelas Gráficas",
  "Young Adult": "Jovem Adulto",
  "Juvenile Fiction": "Ficção Juvenil",
  "Juvenile Nonfiction": "Não Ficção Juvenil",
  "Young Adult Fiction": "Ficção Jovem Adulta",
  "Psychotherapy": "Psicoterapia"
};

export const translateCategories = (category: string): string =>
  categoriesInPortuguese[category] || category;
